name: gha-hello-world
on: [push]


jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-java@v1
        with:
          java-version: '11.0.5'
          architecture: x64
      - run: sbt scalafmtCheckAll scalafmtSbtCheck
  build:
    name: Test
    needs: checks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ['8.0.232', '11.0.5']
        scala: ['2.12.10', '2.13.1']
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
          architecture: x64
      - run: sbt "++${{ matrix.scala}} test"